# Generated by Django 6.0.2 on 2026-02-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_db_schema_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversationlog',
            name='projects_co_project_fcd6af_idx',
        ),
        migrations.RemoveIndex(
            model_name='savedquery',
            name='projects_sa_project_c0fd2d_idx',
        ),
        migrations.RemoveField(
            model_name='savedquery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='savedquery',
            name='project',
        ),
        migrations.DeleteModel(
            name='ConversationLog',
        ),
        migrations.DeleteModel(
            name='SavedQuery',
        ),
    ]
