# Generated by Django 5.2.11 on 2026-03-09 12:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0020_schemastate_add_failed"),
    ]

    operations = [
        # Use RunSQL to convert WorkspaceTenant.id from bigint to uuid
        # (Django cannot cast bigint→uuid directly; we add a new column, populate, swap).
        migrations.RunSQL(
            sql=[
                # 1. Add the new UUID column (nullable initially)
                "ALTER TABLE projects_workspacetenant ADD COLUMN id_new uuid",
                # 2. Populate existing rows with generated UUIDs
                "UPDATE projects_workspacetenant SET id_new = gen_random_uuid()",
                # 3. Set NOT NULL now that all rows have values
                "ALTER TABLE projects_workspacetenant ALTER COLUMN id_new SET NOT NULL",
                # 4. Drop the old integer primary key constraint
                "ALTER TABLE projects_workspacetenant DROP CONSTRAINT projects_workspacetenant_pkey",
                # 5. Drop old id column
                "ALTER TABLE projects_workspacetenant DROP COLUMN id",
                # 6. Rename new column to id
                "ALTER TABLE projects_workspacetenant RENAME COLUMN id_new TO id",
                # 7. Add primary key on the new uuid column
                "ALTER TABLE projects_workspacetenant ADD PRIMARY KEY (id)",
                # 8. Add default for future inserts
                "ALTER TABLE projects_workspacetenant ALTER COLUMN id SET DEFAULT gen_random_uuid()",
            ],
            reverse_sql=[
                # Reverse: convert uuid back to bigint (data loss — only for dev rollback)
                "ALTER TABLE projects_workspacetenant DROP CONSTRAINT projects_workspacetenant_pkey",
                "ALTER TABLE projects_workspacetenant ADD COLUMN id_old bigserial",
                "ALTER TABLE projects_workspacetenant DROP COLUMN id",
                "ALTER TABLE projects_workspacetenant RENAME COLUMN id_old TO id",
                "ALTER TABLE projects_workspacetenant ADD PRIMARY KEY (id)",
            ],
        ),
        migrations.AlterField(
            model_name="workspacetenant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceViewSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("schema_name", models.CharField(max_length=255, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("materializing", "Materializing"),
                            ("expired", "Expired"),
                            ("teardown", "Teardown"),
                            ("failed", "Failed"),
                        ],
                        default="provisioning",
                        max_length=20,
                    ),
                ),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_schema",
                        to="projects.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
