# Generated by Django 5.2.11 on 2026-03-12 12:15

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentLearning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Plain English description of the learning. This is what gets injected into the prompt."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("type_mismatch", "Column type mismatch"),
                            ("filter_required", "Missing required filter"),
                            ("join_pattern", "Correct join pattern"),
                            ("aggregation", "Aggregation gotcha"),
                            ("naming", "Column/table naming convention"),
                            ("data_quality", "Data quality issue"),
                            ("business_logic", "Business logic correction"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "applies_to_tables",
                    models.JSONField(default=list, help_text="Tables this learning applies to."),
                ),
                (
                    "original_error",
                    models.TextField(
                        blank=True, help_text="The error message or suspicious result."
                    ),
                ),
                ("original_sql", models.TextField(blank=True, help_text="The SQL that failed.")),
                ("corrected_sql", models.TextField(blank=True, help_text="The SQL that worked.")),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.5,
                        help_text="0-1 score. Increases when the learning is confirmed useful, decreases if contradicted.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "times_applied",
                    models.IntegerField(
                        default=0, help_text="How many times this learning has been used."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("discovered_in_conversation", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-confidence_score", "-times_applied"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(help_text="Markdown content for this knowledge entry."),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Knowledge entries",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TableKnowledge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("table_name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        help_text="Human-written description of what this table represents and when to use it."
                    ),
                ),
                (
                    "use_cases",
                    models.JSONField(
                        default=list,
                        help_text='What questions this table helps answer. E.g. ["Revenue reporting", "User retention analysis"]',
                    ),
                ),
                (
                    "data_quality_notes",
                    models.JSONField(
                        default=list,
                        help_text='Known quirks. E.g. ["created_at is UTC", "amount is in cents not dollars"]',
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True,
                        help_text="Team or person responsible for this table's data quality.",
                        max_length=255,
                    ),
                ),
                (
                    "refresh_frequency",
                    models.CharField(
                        blank=True,
                        help_text='How often this data updates. E.g. "hourly", "daily at 3am UTC", "real-time"',
                        max_length=100,
                    ),
                ),
                (
                    "related_tables",
                    models.JSONField(
                        default=list,
                        help_text='Tables commonly joined with this one. E.g. [{"table": "users", "join_hint": "orders.user_id = users.id"}]',
                    ),
                ),
                (
                    "column_notes",
                    models.JSONField(
                        default=dict,
                        help_text='Per-column notes. E.g. {"status": "Values: active, churned, trial"}',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Table knowledge",
                "ordering": ["table_name"],
            },
        ),
    ]
