# Generated by Django 5.2.11 on 2026-03-12 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentlearning",
            name="discovered_by_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="agentlearning",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learnings",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="created_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_entries",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="tableknowledge",
            name="updated_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tableknowledge",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table_knowledge",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="agentlearning",
            index=models.Index(
                fields=["workspace", "is_active", "-confidence_score"],
                name="knowledge_a_workspa_d30ff5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tableknowledge",
            unique_together={("workspace", "table_name")},
        ),
    ]
