# Generated by Django 5.2.11 on 2026-02-20 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0005_simplify_knowledge"),
        ("workspace", "0012_add_tenant_workspace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evalrun",
            name="project",
        ),
        migrations.RemoveField(
            model_name="evalrun",
            name="triggered_by",
        ),
        migrations.RemoveField(
            model_name="goldenquery",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="goldenquery",
            name="project",
        ),
        migrations.RemoveIndex(
            model_name="agentlearning",
            name="knowledge_a_project_ab61e4_idx",
        ),
        migrations.RemoveField(
            model_name="agentlearning",
            name="project",
        ),
        migrations.RemoveField(
            model_name="knowledgeentry",
            name="project",
        ),
        # Clear old unique_together BEFORE removing project field
        migrations.AlterUniqueTogether(
            name="tableknowledge",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="tableknowledge",
            name="project",
        ),
        migrations.AddField(
            model_name="agentlearning",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learnings",
                to="workspace.tenantworkspace",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_entries",
                to="workspace.tenantworkspace",
            ),
        ),
        migrations.AddField(
            model_name="tableknowledge",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table_knowledge",
                to="workspace.tenantworkspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tableknowledge",
            unique_together={("workspace", "table_name")},
        ),
        migrations.AddIndex(
            model_name="agentlearning",
            index=models.Index(
                fields=["workspace", "is_active", "-confidence_score"],
                name="knowledge_a_workspa_d30ff5_idx",
            ),
        ),
        migrations.DeleteModel(
            name="EvalRun",
        ),
        migrations.DeleteModel(
            name="GoldenQuery",
        ),
    ]
