# Generated by Django 5.2.11 on 2026-03-02 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0006_rescope_to_workspace"),
        ("workspace", "0017_add_custom_workspace_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tableknowledge",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="agentlearning",
            name="custom_workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learnings",
                to="workspace.customworkspace",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="custom_workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_entries",
                to="workspace.customworkspace",
            ),
        ),
        migrations.AddField(
            model_name="tableknowledge",
            name="custom_workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table_knowledge",
                to="workspace.customworkspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentlearning",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("custom_workspace__isnull", True), ("workspace__isnull", False)),
                    models.Q(("custom_workspace__isnull", False), ("workspace__isnull", True)),
                    _connector="OR",
                ),
                name="agent_learning_one_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("custom_workspace__isnull", True), ("workspace__isnull", False)),
                    models.Q(("custom_workspace__isnull", False), ("workspace__isnull", True)),
                    _connector="OR",
                ),
                name="knowledge_entry_one_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="tableknowledge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("custom_workspace__isnull", True), ("workspace__isnull", False)),
                    models.Q(("custom_workspace__isnull", False), ("workspace__isnull", True)),
                    _connector="OR",
                ),
                name="table_knowledge_one_workspace",
            ),
        ),
    ]
