# Generated by Django 5.2.11 on 2026-02-18 18:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('commcare', 'CommCare HQ'), ('commcare_connect', 'CommCare Connect')], max_length=50)),
                ('tenant_id', models.CharField(help_text='Domain name (CommCare) or organization ID (Connect)', max_length=255)),
                ('tenant_name', models.CharField(help_text='Human-readable tenant name', max_length=255)),
                ('last_selected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_selected_at', 'tenant_name'],
                'unique_together': {('user', 'provider', 'tenant_id')},
            },
        ),
    ]
