# Generated by Django 5.2.11 on 2026-04-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_deduplicate_tenant_memberships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="provider",
            field=models.CharField(
                choices=[
                    ("commcare", "CommCare HQ"),
                    ("commcare_connect", "CommCare Connect"),
                    ("ocs", "Open Chat Studio"),
                ],
                max_length=50,
            ),
        ),
    ]
