# Generated by Django 5.2.11 on 2026-02-18 19:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0010_drop_datasource_tables"),
        ("users", "0003_tenantmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantSchema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("schema_name", models.CharField(max_length=255, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("materializing", "Materializing"),
                            ("expired", "Expired"),
                            ("teardown", "Teardown"),
                        ],
                        default="provisioning",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemas",
                        to="users.tenantmembership",
                    ),
                ),
            ],
            options={
                "db_table": "projects_tenantschema",
                "ordering": ["-last_accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterializationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pipeline", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("loading", "Loading"),
                            ("transforming", "Transforming"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materialization_runs",
                        to="workspace.tenantschema",
                    ),
                ),
            ],
            options={
                "db_table": "projects_materializationrun",
                "ordering": ["-started_at"],
            },
        ),
    ]
