# Generated by Django 5.2.11 on 2026-02-24 15:00

import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0013_remove_project_models"),
        ("users", "0004_add_tenantcredential"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metadata",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Provider-specific metadata blob. Structure defined by the loader.",
                        schema=dict,
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this metadata was last successfully fetched from the provider",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="users.tenantmembership",
                    ),
                ),
            ],
            options={
                "db_table": "projects_tenantmetadata",
                "verbose_name": "Tenant Metadata",
                "verbose_name_plural": "Tenant Metadata",
            },
        ),
    ]
