# Generated by Django 5.2.11 on 2026-02-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0014_tenantmetadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materializationrun",
            name="state",
            field=models.CharField(
                choices=[
                    ("started", "Started"),
                    ("discovering", "Discovering"),
                    ("loading", "Loading"),
                    ("transforming", "Transforming"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="started",
                max_length=20,
            ),
        ),
    ]
