# Generated by Django 5.2.11 on 2026-03-12 12:15

import uuid

import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterializationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pipeline", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("discovering", "Discovering"),
                            ("loading", "Loading"),
                            ("transforming", "Transforming"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metadata",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Provider-specific metadata blob. Structure defined by the loader.",
                        schema=dict,
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this metadata was last successfully fetched from the provider",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant Metadata",
                "verbose_name_plural": "Tenant Metadata",
            },
        ),
        migrations.CreateModel(
            name="TenantSchema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("schema_name", models.CharField(max_length=255, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("materializing", "Materializing"),
                            ("expired", "Expired"),
                            ("teardown", "Teardown"),
                            ("failed", "Failed"),
                        ],
                        default="provisioning",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-last_accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "is_auto_created",
                    models.BooleanField(
                        default=False,
                        help_text="True if this workspace was automatically created during OAuth login.",
                    ),
                ),
                ("system_prompt", models.TextField(blank=True)),
                ("data_dictionary", models.JSONField(blank=True, null=True)),
                ("data_dictionary_generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("read_write", "Read/Write"),
                            ("manage", "Manage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceTenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceViewSchema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("schema_name", models.CharField(max_length=255, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("materializing", "Materializing"),
                            ("expired", "Expired"),
                            ("teardown", "Teardown"),
                            ("failed", "Failed"),
                        ],
                        default="provisioning",
                        max_length=20,
                    ),
                ),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
