# Generated by Django 5.2.11 on 2026-03-12 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmetadata",
            name="tenant_membership",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to="users.tenantmembership",
            ),
        ),
        migrations.AddField(
            model_name="tenantschema",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schemas",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="materializationrun",
            name="tenant_schema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materialization_runs",
                to="workspaces.tenantschema",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="workspacetenant",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_tenants",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="workspacetenant",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_tenants",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="tenants",
            field=models.ManyToManyField(
                related_name="workspaces", through="workspaces.WorkspaceTenant", to="users.tenant"
            ),
        ),
        migrations.AddField(
            model_name="workspaceviewschema",
            name="workspace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_schema",
                to="workspaces.workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspacemembership",
            unique_together={("workspace", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="workspacetenant",
            unique_together={("workspace", "tenant")},
        ),
    ]
