#!/bin/bash
# Fetches infrastructure values from the CloudFormation stack and writes .env.deploy.
# Run this once after stack creation, or any time infra changes (e.g. new EC2 IP).
#
# Usage:
#   ./scripts/fetch-deploy-env.sh           # uses default profile "scout"
#   AWS_PROFILE=myprofile ./scripts/fetch-deploy-env.sh
#
# The generated .env.deploy is gitignored and sourced before running kamal deploy.

set -euo pipefail

PROFILE="${AWS_PROFILE:-scout}"
STACK_NAME="scout-production"
REGION="us-east-1"
OUTPUT_FILE=".env.deploy"

# Ensure we have valid AWS credentials
if ! aws sts get-caller-identity --profile "$PROFILE" &>/dev/null; then
  echo "No valid AWS session. Logging in..."
  aws sso login --profile "$PROFILE"
fi

echo "Fetching CloudFormation outputs from stack '$STACK_NAME'..."

OUTPUTS=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --query 'Stacks[0].Outputs' \
  --output json \
  --region "$REGION" \
  --profile "$PROFILE")

# Parse outputs into env vars
get_output() {
  echo "$OUTPUTS" | python3 -c \
    "import sys,json; key=sys.argv[1]; outputs=json.load(sys.stdin); print(next(o['OutputValue'] for o in outputs if o['OutputKey']==key))" "$1"
}

EC2_IP=$(get_output "EC2PublicIP")
RDS_ENDPOINT=$(get_output "RDSEndpoint")
RDS_SECRET_ARN=$(get_output "RDSSecretArn")
REDIS_ENDPOINT=$(get_output "RedisEndpoint")
ECR_REGISTRY=$(get_output "ECRRegistry")
GITHUB_DEPLOY_ROLE_ARN=$(get_output "GitHubDeployRoleArn")

cat > "$OUTPUT_FILE" <<EOF
# Auto-generated by scripts/fetch-deploy-env.sh
# Do not commit — this file is gitignored.
# Re-run the script to refresh after infrastructure changes.

export SCOUT_EC2_IP=$EC2_IP
export SCOUT_RDS_ENDPOINT=$RDS_ENDPOINT
export SCOUT_RDS_SECRET_ARN=$RDS_SECRET_ARN
export SCOUT_REDIS_ENDPOINT=$REDIS_ENDPOINT
export SCOUT_ECR_REGISTRY=$ECR_REGISTRY
export SCOUT_GITHUB_DEPLOY_ROLE_ARN=$GITHUB_DEPLOY_ROLE_ARN
EOF

echo "Written to $OUTPUT_FILE:"
cat "$OUTPUT_FILE"
