# Generated by Django 5.2.11 on 2026-03-12 12:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Prompt template with {{variable}} placeholders. Supports markdown.",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of variable definitions for the recipe.",
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="If true, all project members can view and run this recipe.",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If true, accessible via public share link without authentication.",
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Token for public share URL. Auto-generated when is_public is set.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RecipeRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "variable_values",
                    models.JSONField(
                        default=dict, help_text="Actual variable values used for this run."
                    ),
                ),
                (
                    "step_results",
                    models.JSONField(
                        blank=True, default=list, help_text="Results from each step execution."
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_shared",
                    models.BooleanField(default=False, help_text="Visible to all project members."),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If true, accessible via public share link without authentication.",
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Token for public share URL. Auto-generated when is_public is set.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecipeStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Execution order of this step (starting from 1)."
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(help_text="Prompt template with {{variable}} placeholders."),
                ),
                (
                    "expected_tool",
                    models.CharField(
                        blank=True,
                        help_text="Optional: expected tool the agent should use (e.g., 'execute_sql').",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of what this step accomplishes."
                    ),
                ),
            ],
            options={
                "ordering": ["recipe", "order"],
            },
        ),
    ]
