# Generated by Django 5.2.11 on 2026-03-12 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0002_initial"),
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="projects.workspace",
            ),
        ),
        migrations.AddField(
            model_name="reciperun",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="recipes.recipe",
            ),
        ),
        migrations.AddField(
            model_name="reciperun",
            name="run_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipe_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="recipes.recipe",
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["workspace", "is_shared"], name="recipes_rec_workspa_943bef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["workspace", "created_by"], name="recipes_rec_workspa_212272_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reciperun",
            index=models.Index(
                fields=["recipe", "-created_at"], name="recipes_rec_recipe__692d15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reciperun",
            index=models.Index(
                fields=["run_by", "-created_at"], name="recipes_rec_run_by__25687d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reciperun",
            index=models.Index(fields=["status"], name="recipes_rec_status_26aa34_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="recipestep",
            unique_together={("recipe", "order")},
        ),
    ]
