# Generated by Django 5.2.11 on 2026-03-12 12:15

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Display title for the artifact.", max_length=500),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this artifact does or shows.",
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("react", "React Component"),
                            ("html", "HTML Document"),
                            ("markdown", "Markdown Document"),
                            ("plotly", "Plotly Chart"),
                            ("svg", "SVG Graphic"),
                        ],
                        help_text="The type of artifact (react, html, markdown, plotly, svg).",
                        max_length=20,
                    ),
                ),
                ("code", models.TextField(help_text="Source code for the artifact.")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data for the artifact (e.g., chart data, configuration).",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Version number of this artifact.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        db_index=True,
                        help_text="Thread ID of the conversation that created this artifact.",
                        max_length=255,
                    ),
                ),
                (
                    "source_queries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="SQL queries that generated the data for this artifact.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Artifact",
                "verbose_name_plural": "Artifacts",
                "ordering": ["-created_at"],
            },
        ),
    ]
