# Generated by Django 5.2.11 on 2026-03-12 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artifacts", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this artifact.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_artifacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="parent_artifact",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous version of this artifact for version tracking.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_versions",
                to="artifacts.artifact",
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="The workspace this artifact belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["workspace", "-created_at"], name="artifacts_a_workspa_a5ce68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["created_by", "-created_at"], name="artifacts_a_created_49dabc_idx"
            ),
        ),
    ]
