# Generated by Django 6.0.2 on 2026-02-05 19:35

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number of this artifact.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='sharedartifact',
            index=models.Index(fields=['artifact', '-created_at'], name='artifacts_s_artifac_fe4956_idx'),
        ),
    ]
