# Generated by Django 5.2.11 on 2026-02-18 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_add_thread_sharing_fields"),
        ("workspace", "0011_tenantschema_materializationrun"),
        ("users", "0003_tenantmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="tenant_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="users.tenantmembership",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="workspace.project",
            ),
        ),
    ]
