# Generated by Django 5.2.11 on 2026-03-02 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_rescope_to_workspace"),
        ("workspace", "0017_add_custom_workspace_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="custom_workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="workspace.customworkspace",
            ),
        ),
    ]
